chore: Fix flaky test in unsafeOptionalDataVia
apache/pekko pull request #1611
Opened 2024-12-17 15:18 UTC by He-Pin

refs: https://github.com/apache/pekko/issues/1610

Motivation:
Fix flaky test in unsafeOptionalDataVia

Modification:
1. change to `expectNextN`, where merge is been used ,so order is undefined.
2. avoid allocation

2024-12-17 15:20 UTC, mdedetrich approved these changes
lgtm

2024-12-17 15:33 UTC, raboof reviewed
shouldn't `unsafeOptionalDataVia` keep the order?

I thought the 'unsafe' aspect was the `Flow` parameter must be a flow that produces 1 output per input without reordering (and we can't 'safely' express that in the typesystem), but as long as that's the case (as it is here) it should keep order.

Shouldn't we change the implementation rather than the test?

2024-12-17 15:34 UTC, He-Pin commented
@raboof That's what's I'm wondering, because the current design ,it can not keep order, not sure if that's how @mdedetrich expected it works.

2024-12-17 15:37 UTC, mdedetrich commented
Let me retract my approval, I didn't pay attention to the change.

Indeed the ordering of the elements should not change, @raboof is correct where the unsafe part pertains to the fact that you could provide a Flow that reorders/drops elements and there isn't any check for this but assuming you provide a flow that only transforms elements than ordering should be retained.

Funnily enough I haven't experienced this in production, ill have a look at it.

2024-12-17 15:38 UTC, He-Pin commented
@mdedetrich Can you give some more context of the current design？

2024-12-17 15:38 UTC, mdedetrich requested changes
Blocking for now as the ordering is meant to be determinstic, prob the implementation needs to be fixed.

2024-12-17 15:39 UTC, mdedetrich commented
> @mdedetrich Can you give some more context of the current design？

So the context is primarily when using kafka cursors with FlowWithContext/SourceWithContext. This feature lets you provide a flow that only transforms the data portion of the stream while leaving the context part untouched (which is critical when dealing with Kafka and committing cursors).

2024-12-17 15:40 UTC, He-Pin commented
Let me update it, I can workout a solution.

2024-12-17 18:22 UTC, He-Pin commented
@raboof @mdedetrich @pjfanning I think it should be OK now, it now track the origin order with an index and then merge back with the same index.

2024-12-17 18:24 UTC, He-Pin commented on stream/src/main/scala/org/apache/pekko/stream/scaladsl/SourceWithContext.scala
> +        partition.out(0).asInstanceOf[Outlet[(Option[FOut], IndexedCtx)]] ~> mergeSequence.in(0)
cast here to avoid allocation, it will always be `None` because of partition

2024-12-17 19:10 UTC, pjfanning commented
> Do we know if the test runs in PR CI builds? I did a quick check of the test logs and didn't find a match.

I found `must Apply a viaFlow with optional elements using unsafeOptionalVia (52 milliseconds)` so the test is running.

2024-12-17 19:10 UTC, pjfanning approved these changes
lgtm

2024-12-17 19:15 UTC, He-Pin commented on stream/src/main/scala/org/apache/pekko/stream/scaladsl/SourceWithContext.scala
> +        case class IndexedCtx(idx: Long, ctx: Ctx)
extra allocation here

2024-12-17 21:05 UTC, mdedetrich approved these changes

2024-12-18 02:43 UTC, merged

2024-12-18 02:43 UTC, He-Pin commented
Thanks for the review

2025-01-04 20:19 UTC, pjfanning commented
It is in v1.1.3-RC1.
Have a look at https://github.com/apache/pekko/commit/7184dadf4a1d57ac07cd4eb26b67b3f8b5ccf47d
and the tags that it is in (v1.1.3-RC1 and v1.2.0-M0).

2025-01-04 22:40 UTC, He-Pin commented
Thanks  , seems there are some problem on my local history